# Form implementation generated from reading ui file 'gisWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_GisWindow(object):
    def setupUi(self, GisWindow):
        GisWindow.setObjectName("GisWindow")
        GisWindow.resize(800, 600)
        GisWindow.setIconSize(QtCore.QSize(30, 30))
        #GisWindow.setWindowFlag(QtCore.Qt.FramelessWindowHint) 
        self.MainWidget = QtWidgets.QWidget(parent=GisWindow)
        self.MainWidget.setStyleSheet("QWidget#MainWidget{background-color: rgb(255, 255, 255);"
                                              "border: 1px solid rgb(189, 189, 189);}\n"
                                      "QFrame#PathFrame{border-style: none;}\n"
                                      "QPushButton{background-color: rgb(1, 139, 254);\n"
                                                  "border: 1px solid rgb(116, 116, 116);\n"
                                                  "border-radius: 10px;}\n"
                                      "QAbstractButton{color: rgb(255, 255, 255);}\n"
                                      "QLineEdit{border: 1px solid rgb(116, 116, 116);}\n"
                                      "QGraphicsView{border: 2px solid rgb(0, 0, 0);}")
        self.MainWidget.setObjectName("MainWidget")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.MainWidget)
        self.verticalLayout.setContentsMargins(15, 20, 15, 20)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")

        self.PathFrame = QtWidgets.QFrame(parent=self.MainWidget)
        self.PathFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.PathFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.PathFrame.setObjectName("PathFrame")

        self.horizontalLayout = QtWidgets.QHBoxLayout(self.PathFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.PathLineEdit = QtWidgets.QLineEdit(parent=self.PathFrame)
        self.PathLineEdit.setFixedHeight(30)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PathLineEdit.setFont(font)
        self.PathLineEdit.setObjectName("PathLineEdit")
        self.PathLineEdit.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)

        self.horizontalLayout.addWidget(self.PathLineEdit)

        self.PathPushButton = QtWidgets.QPushButton(parent=self.PathFrame)
        self.PathPushButton.setFixedSize(150, 30)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PathPushButton.setFont(font)
        self.PathPushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.PathPushButton.setObjectName("PathPushButton")

        self.horizontalLayout.addWidget(self.PathPushButton)

        self.verticalLayout.addWidget(self.PathFrame)

        #self.MapGraphicsView = QtWidgets.QGraphicsView(parent=self.MainWidget)
        #self.MapGraphicsView.setObjectName("MapGraphicsView")

        #self.verticalLayout.addWidget(self.MapGraphicsView)

        self.MessageLabel = QtWidgets.QLabel(parent=self.MainWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.MessageLabel.setFont(font)
        self.MessageLabel.setObjectName("MessageLabel")
        self.verticalLayout.addWidget(self.MessageLabel)
        GisWindow.setCentralWidget(self.MainWidget)

        self.retranslateUi(GisWindow)
        QtCore.QMetaObject.connectSlotsByName(GisWindow)

    def retranslateUi(self, GisWindow):
        _translate = QtCore.QCoreApplication.translate
        GisWindow.setWindowTitle(_translate("GisWindow", "Тестовая ГИС"))
        self.PathPushButton.setText(_translate("GisWindow", "Обзор"))
        self.MessageLabel.setText(_translate("GisWindow", ""))
